behaviors:
  FetchGamePhysics:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: resnet
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: resnet
          goal_conditioning_type: hyper
          deterministic: false
      rnd:
        learning_rate: 3e-4
        strength: 0.01
        gamma: 0.99
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: resnet
          goal_conditioning_type: hyper
          deterministic: false
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 15000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
environment_parameters:
  angle_threshold:
    curriculum:
      - name: LessonA
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0
        value: 50
      - name: LessonB
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.2
        value: 45
      - name: LessonC
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.4
        value: 40
      - name: LessonD
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 35
      - name: LessonE
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 30
      - name: LessonF
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.75
        value: 20
      - name: LessonG
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 15
      - name: LessonFinal
        value: 10
